# Generated by Django 4.1.5 on 2023-02-27 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=50)),
                ('Baniere', models.ImageField(upload_to='Banieres/')),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Banieres',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Slogan', models.CharField(max_length=50)),
                ('OfficeHour', models.CharField(max_length=15)),
                ('CompanyLogo', models.ImageField(upload_to='CompanyLogo/')),
                ('CompanyAbout', models.TextField(max_length=500)),
                ('CompanyMission', models.TextField(max_length=500)),
                ('CompanyVision', models.TextField(max_length=500)),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entreprise',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Logo', models.ImageField(upload_to='partners/')),
                ('Website_url', models.URLField(blank=True, null=True)),
                ('Publish_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Partenaires',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Poster', models.ImageField(upload_to='Projects/')),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Remaining', 'Remaining')], max_length=20)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('Partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partner')),
            ],
            options={
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Poster', models.ImageField(upload_to='Services/')),
                ('Publish_date', models.DateTimeField(auto_now_add=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(default='avatar.png', null=True, upload_to='TeamMembers/')),
                ('Name', models.CharField(max_length=50)),
                ('Comment', models.CharField(max_length=250)),
                ('Work', models.CharField(max_length=25)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Description', models.TextField()),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(default='avatar.png', null=True, upload_to='TeamMembers/')),
                ('FacebookLink', models.CharField(blank=True, max_length=50, null=True)),
                ('TwitterLink', models.CharField(blank=True, max_length=50, null=True)),
                ('LinkdinLink', models.CharField(blank=True, max_length=50, null=True)),
                ('InstagramLink', models.CharField(blank=True, max_length=50, null=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('Service', models.ManyToManyField(to='main.service')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster', models.ImageField(upload_to='Projects/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(default='avatar.png', null=True, upload_to='Customers/')),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(max_length=6)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Adress', models.CharField(max_length=30)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('Status', models.CharField(choices=[('Unread', 'Unread'), ('Readed', 'Readed')], max_length=20)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=150)),
                ('whatsapp', models.BooleanField(default=False)),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name_plural': 'Contacts Entreprise',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=150)),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name_plural': 'Emails Entreprise',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=150)),
                ('Publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name_plural': 'Adresses Entreprise',
            },
        ),
    ]
